### ISSUE TITLE
Upgrade to css-loader@1.0.0

### ISSUE THREAD

**Issue by xstable** [xstable/xst_google_events#5]
Used css-loader Component has an security-issue with js-yaml@3.7.0 which is a dependency of css-loader.
Upgrade css-loader to 1.0.0 to fix this issue.

**Comment by ohana54** [comment]
I'm on it

**Comment by ohana54** [comment]
BTW, css-loader@1.0.0 requires webpack v4, I'll open a PR for upgrading webpack first

**Comment by ohana54** [comment]
Eventually did it in a single PR - #12
