### ISSUE TITLE
add i18n Support

### ISSUE THREAD

**Issue by xstable** [xstable/xst_google_events#8]
use Language-Files for Labels (Table, Buttons etc.)

**Comment by mattb555** [comment]
I'm going to go ahead and take a crack at this tonight

**Comment by mattb555** [comment]
Just to report back, I've implemented i18next functionality into the program, before I make a pull request though I need to factor out a few more strings and I also want to implement the logic that auto decides language based on browser settings, unless you want me to make a language chooser of some description.

I went ahead and just wrapped it up and made the pull request, the browser based detection is fine, but it's kinda hard to trick Chrome into thinking I speak German so adding a language selector would be a good idea.

**Comment by xstable** [comment]
@mattb555 hey, great, thank you for your effort.
Automatic Language-Detection would be a nice feature! 
Would be nice if this can be toggled by config-options. (ON = default, OFF = optional if needed via config parameter)

Maybe same with Language selector. This way everybody can decide to use autodetect or lang-switch.
